<?php
/**
 * WHOIS Sunucu Listesi
 * Tüm uzantılar dahil - Türkiye uzantıları dahil
 */

return [
    // ===== TÜRKİYE UZANTILARI =====
    // Doğru sunucu: whois.metu.edu.tr | Müsait pattern: "No match found"
    'com.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'net.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'org.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'gov.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'edu.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'mil.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'k12.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'av.tr'     => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'dr.tr'     => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'bbs.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'tel.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'info.tr'   => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'tv.tr'     => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'bel.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'pol.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'tsk.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'name.tr'   => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'web.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'gen.tr'    => ['host' => 'whois.metu.edu.tr',     'pattern' => 'no match found'],
    'istanbul'  => ['host' => 'whois.afilias-srs.net', 'pattern' => 'not found'],
    'ist'       => ['host' => 'whois.nic.ist',         'pattern' => 'not found'],
    'istanbul'  => ['host' => 'whois.afilias-srs.net', 'pattern' => 'not found'],
    'ankara'    => ['host' => 'whois.nic.ankara',      'pattern' => 'not found'],
    'antalya'   => ['host' => 'whois.nic.antalya',     'pattern' => 'not found'],
    'izmir'     => ['host' => 'whois.nic.izmir',       'pattern' => 'not found'],

    // ===== GENEL (gTLD) UZANTILAR =====
    'com'       => ['host' => 'whois.verisign-grs.com','pattern' => 'no match'],
    'net'       => ['host' => 'whois.verisign-grs.com','pattern' => 'no match'],
    'org'       => ['host' => 'whois.pir.org',         'pattern' => 'not found'],
    'info'      => ['host' => 'whois.afilias.net',     'pattern' => 'not found'],
    'biz'       => ['host' => 'whois.biz',             'pattern' => 'not found'],
    'name'      => ['host' => 'whois.nic.name',        'pattern' => 'not found'],
    'mobi'      => ['host' => 'whois.dotmobiregistry.net', 'pattern' => 'not found'],
    'tel'       => ['host' => 'whois.nic.tel',         'pattern' => 'not found'],
    'asia'      => ['host' => 'whois.nic.asia',        'pattern' => 'not found'],
    'int'       => ['host' => 'whois.iana.org',        'pattern' => 'not found'],
    'museum'    => ['host' => 'whois.museum',          'pattern' => 'not found'],
    'travel'    => ['host' => 'whois.nic.travel',      'pattern' => 'not found'],
    'aero'      => ['host' => 'whois.aero',            'pattern' => 'not found'],
    'coop'      => ['host' => 'whois.nic.coop',        'pattern' => 'not found'],
    'jobs'      => ['host' => 'jobswhois.verisign-grs.com', 'pattern' => 'not found'],
    'pro'       => ['host' => 'whois.dotproregistry.net', 'pattern' => 'not found'],
    'cat'       => ['host' => 'whois.cat',             'pattern' => 'not found'],
    'post'      => ['host' => 'whois.dotpostregistry.net', 'pattern' => 'not found'],
    'xxx'       => ['host' => 'whois.nic.xxx',         'pattern' => 'not found'],
    'edu'       => ['host' => 'whois.educause.edu',    'pattern' => 'not found'],
    'gov'       => ['host' => 'whois.dotgov.gov',      'pattern' => 'not found'],
    'mil'       => ['host' => 'whois.nic.mil',         'pattern' => 'not found'],
    'arpa'      => ['host' => 'whois.iana.org',        'pattern' => 'not found'],

    // ===== YENİ gTLD UZANTILAR =====
    'app'       => ['host' => 'whois.nic.app',         'pattern' => 'not found'],
    'dev'       => ['host' => 'whois.nic.google',      'pattern' => 'not found'],
    'web'       => ['host' => 'whois.nic.web',         'pattern' => 'not found'],
    'shop'      => ['host' => 'whois.nic.shop',        'pattern' => 'not found'],
    'store'     => ['host' => 'whois.nic.store',       'pattern' => 'not found'],
    'online'    => ['host' => 'whois.nic.online',      'pattern' => 'not found'],
    'site'      => ['host' => 'whois.nic.site',        'pattern' => 'not found'],
    'tech'      => ['host' => 'whois.nic.tech',        'pattern' => 'not found'],
    'io'        => ['host' => 'whois.nic.io',          'pattern' => 'not found'],
    'co'        => ['host' => 'whois.nic.co',          'pattern' => 'not found'],
    'me'        => ['host' => 'whois.nic.me',          'pattern' => 'not found'],
    'tv'        => ['host' => 'whois.nic.tv',          'pattern' => 'not found'],
    'cc'        => ['host' => 'whois.nic.cc',          'pattern' => 'not found'],
    'ws'        => ['host' => 'whois.website.ws',      'pattern' => 'not found'],
    'us'        => ['host' => 'whois.nic.us',          'pattern' => 'not found'],
    'eu'        => ['host' => 'whois.eu',              'pattern' => 'not found'],
    'uk'        => ['host' => 'whois.nic.uk',          'pattern' => 'not registered'],
    'co.uk'     => ['host' => 'whois.nic.uk',          'pattern' => 'not registered'],
    'org.uk'    => ['host' => 'whois.nic.uk',          'pattern' => 'not registered'],
    'me.uk'     => ['host' => 'whois.nic.uk',          'pattern' => 'not registered'],
    'de'        => ['host' => 'whois.denic.de',        'pattern' => 'not found'],
    'fr'        => ['host' => 'whois.nic.fr',          'pattern' => 'not found'],
    'es'        => ['host' => 'whois.nic.es',          'pattern' => 'not found'],
    'it'        => ['host' => 'whois.nic.it',          'pattern' => 'available'],
    'nl'        => ['host' => 'whois.domain-registry.nl', 'pattern' => 'not found'],
    'be'        => ['host' => 'whois.dns.be',          'pattern' => 'not found'],
    'ch'        => ['host' => 'whois.nic.ch',          'pattern' => 'not found'],
    'at'        => ['host' => 'whois.nic.at',          'pattern' => 'not found'],
    'pl'        => ['host' => 'whois.dns.pl',          'pattern' => 'not found'],
    'ru'        => ['host' => 'whois.tcinet.ru',       'pattern' => 'no entries found'],
    'cn'        => ['host' => 'whois.cnnic.cn',        'pattern' => 'no matching record'],
    'jp'        => ['host' => 'whois.jprs.jp',         'pattern' => 'no match'],
    'au'        => ['host' => 'whois.auda.org.au',     'pattern' => 'not found'],
    'com.au'    => ['host' => 'whois.auda.org.au',     'pattern' => 'not found'],
    'net.au'    => ['host' => 'whois.auda.org.au',     'pattern' => 'not found'],
    'ca'        => ['host' => 'whois.cira.ca',         'pattern' => 'not found'],
    'in'        => ['host' => 'whois.registry.in',     'pattern' => 'not found'],
    'br'        => ['host' => 'whois.registro.br',     'pattern' => 'not found'],
    'com.br'    => ['host' => 'whois.registro.br',     'pattern' => 'not found'],
    'mx'        => ['host' => 'whois.mx',              'pattern' => 'not found'],
    'com.mx'    => ['host' => 'whois.mx',              'pattern' => 'not found'],
    'ar'        => ['host' => 'whois.nic.ar',          'pattern' => 'not found'],
    'com.ar'    => ['host' => 'whois.nic.ar',          'pattern' => 'not found'],
    'za'        => ['host' => 'whois.registry.net.za', 'pattern' => 'not found'],
    'co.za'     => ['host' => 'whois.co.za',           'pattern' => 'not found'],
    'nz'        => ['host' => 'whois.irs.net.nz',      'pattern' => 'not found'],
    'co.nz'     => ['host' => 'whois.irs.net.nz',      'pattern' => 'not found'],
    'sg'        => ['host' => 'whois.sgnic.sg',        'pattern' => 'not found'],
    'com.sg'    => ['host' => 'whois.sgnic.sg',        'pattern' => 'not found'],
    'hk'        => ['host' => 'whois.hkirc.hk',       'pattern' => 'not found'],
    'com.hk'    => ['host' => 'whois.hkirc.hk',       'pattern' => 'not found'],
    'kr'        => ['host' => 'whois.kr',              'pattern' => 'not found'],
    'tw'        => ['host' => 'whois.twnic.net.tw',    'pattern' => 'not found'],
    'se'        => ['host' => 'whois.iis.se',          'pattern' => 'not found'],
    'no'        => ['host' => 'whois.norid.no',        'pattern' => 'not found'],
    'dk'        => ['host' => 'whois.dk-hostmaster.dk','pattern' => 'not found'],
    'fi'        => ['host' => 'whois.ficora.fi',       'pattern' => 'not found'],
    'pt'        => ['host' => 'whois.dns.pt',          'pattern' => 'not found'],
    'gr'        => ['host' => 'whois.ics.forth.gr',    'pattern' => 'not found'],
    'cz'        => ['host' => 'whois.nic.cz',          'pattern' => 'not found'],
    'sk'        => ['host' => 'whois.sk-nic.sk',       'pattern' => 'not found'],
    'hu'        => ['host' => 'whois.nic.hu',          'pattern' => 'not found'],
    'ro'        => ['host' => 'whois.rotld.ro',        'pattern' => 'not found'],
    'bg'        => ['host' => 'whois.register.bg',     'pattern' => 'not found'],
    'rs'        => ['host' => 'whois.rnids.rs',        'pattern' => 'not found'],
    'hr'        => ['host' => 'whois.dns.hr',          'pattern' => 'not found'],
    'si'        => ['host' => 'whois.arnes.si',        'pattern' => 'not found'],
    'lt'        => ['host' => 'whois.domreg.lt',       'pattern' => 'not found'],
    'lv'        => ['host' => 'whois.nic.lv',          'pattern' => 'not found'],
    'ee'        => ['host' => 'whois.tld.ee',          'pattern' => 'not found'],
    'ie'        => ['host' => 'whois.domainregistry.ie','pattern' => 'not found'],
    'is'        => ['host' => 'whois.isnic.is',        'pattern' => 'no entries found'],
    'lu'        => ['host' => 'whois.dns.lu',          'pattern' => 'not found'],
    'li'        => ['host' => 'whois.nic.li',          'pattern' => 'not found'],
    'mc'        => ['host' => 'whois.ripe.net',        'pattern' => 'not found'],
    'ua'        => ['host' => 'whois.ua',              'pattern' => 'not found'],
    'by'        => ['host' => 'whois.cctld.by',        'pattern' => 'not found'],
    'md'        => ['host' => 'whois.nic.md',          'pattern' => 'not found'],
    'il'        => ['host' => 'whois.isoc.org.il',     'pattern' => 'not found'],
    'sa'        => ['host' => 'whois.nic.net.sa',      'pattern' => 'not found'],
    'ae'        => ['host' => 'whois.aeda.net.ae',     'pattern' => 'not found'],
    'eg'        => ['host' => 'whois.ripe.net',        'pattern' => 'not found'],
    'ma'        => ['host' => 'whois.iam.net.ma',      'pattern' => 'not found'],

    // Yeni Popüler gTLD'ler
    'club'      => ['host' => 'whois.nic.club',        'pattern' => 'not found'],
    'xyz'       => ['host' => 'whois.nic.xyz',         'pattern' => 'not found'],
    'top'       => ['host' => 'whois.nic.top',         'pattern' => 'not found'],
    'live'      => ['host' => 'whois.afilias-srs.net', 'pattern' => 'not found'],
    'news'      => ['host' => 'whois.afilias-srs.net', 'pattern' => 'not found'],
    'media'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'digital'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'agency'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'studio'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'design'    => ['host' => 'whois.nic.design',      'pattern' => 'not found'],
    'art'       => ['host' => 'whois.art',             'pattern' => 'not found'],
    'photography'=> ['host' => 'whois.donuts.co',      'pattern' => 'not found'],
    'email'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'blog'      => ['host' => 'whois.nic.blog',        'pattern' => 'not found'],
    'fun'       => ['host' => 'whois.nic.fun',         'pattern' => 'not found'],
    'games'     => ['host' => 'whois.nic.games',       'pattern' => 'not found'],
    'health'    => ['host' => 'whois.afilias-srs.net', 'pattern' => 'not found'],
    'fitness'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'finance'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'bank'      => ['host' => 'whois.nic.bank',        'pattern' => 'not found'],
    'legal'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'academy'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'school'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'university'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'science'   => ['host' => 'whois.nic.science',     'pattern' => 'not found'],
    'solutions' => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'network'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'systems'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'software'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'hosting'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'cloud'     => ['host' => 'whois.nic.cloud',       'pattern' => 'not found'],
    'global'    => ['host' => 'whois.dotglobal.com',   'pattern' => 'not found'],
    'world'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'zone'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'space'     => ['host' => 'whois.nic.space',       'pattern' => 'not found'],
    'land'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'city'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'center'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'plus'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'pro'       => ['host' => 'whois.dotproregistry.net','pattern' => 'not found'],
    'expert'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'guru'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'ninja'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'rocks'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'life'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'today'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'events'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'social'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'community' => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'group'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'link'      => ['host' => 'whois.uniregistry.net', 'pattern' => 'not found'],
    'click'     => ['host' => 'whois.uniregistry.net', 'pattern' => 'not found'],
    'company'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'business'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'ventures'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'management'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'services'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'support'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'consulting'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'marketing' => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'works'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'properties'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'estate'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'rentals'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'holdings'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'capital'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'foundation'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'care'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'clinic'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'dental'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'run'       => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'show'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'movie'     => ['host' => 'whois.nic.movie',       'pattern' => 'not found'],
    'music'     => ['host' => 'whois.nic.music',       'pattern' => 'not found'],
    'pizza'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'cafe'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'kitchen'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'restaurant'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'food'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'beer'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'holiday'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'tours'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'travel'    => ['host' => 'whois.nic.travel',      'pattern' => 'not found'],
    'flights'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'taxi'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'boutique'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'clothing'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'fashion'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'style'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'jewelry'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'watch'     => ['host' => 'whois.nic.watch',       'pattern' => 'not found'],
    'bike'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'solar'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'energy'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'lawyer'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'attorney'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'accountant'=> ['host' => 'whois.nic.accountant',  'pattern' => 'not found'],
    'tax'       => ['host' => 'whois.nic.tax',         'pattern' => 'not found'],
    'tools'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'technology'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'media'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'video'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'photo'     => ['host' => 'whois.uniregistry.net', 'pattern' => 'not found'],
    'photos'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'pics'      => ['host' => 'whois.uniregistry.net', 'pattern' => 'not found'],
    'pictures'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'graphics'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'gallery'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'immobilien'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'immo'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'contractors'=> ['host' => 'whois.donuts.co',      'pattern' => 'not found'],
    'builders'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'construction'=> ['host' => 'whois.donuts.co',     'pattern' => 'not found'],
    'cleaning'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'plumbing'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'florist'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'garden'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'organic'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'church'    => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'charity'   => ['host' => 'whois.nic.charity',     'pattern' => 'not found'],
    'vote'      => ['host' => 'whois.afilias.net',     'pattern' => 'not found'],
    'democrat'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'republican'=> ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'navy'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'army'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'airforce'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'vet'       => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'trading'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'auction'   => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'cash'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'money'     => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'fund'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'investments'=> ['host' => 'whois.donuts.co',      'pattern' => 'not found'],
    'diamonds'  => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'gold'      => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'black'     => ['host' => 'whois.afilias.net',     'pattern' => 'not found'],
    'blue'      => ['host' => 'whois.afilias.net',     'pattern' => 'not found'],
    'pink'      => ['host' => 'whois.afilias.net',     'pattern' => 'not found'],
    'red'       => ['host' => 'whois.donuts.co',       'pattern' => 'not found'],
    'green'     => ['host' => 'whois.dotgreen.com',    'pattern' => 'not found'],
    'eco'       => ['host' => 'whois.nic.eco',         'pattern' => 'not found'],
];
